# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=/home/zhaoxu/.oh-my-zsh
export TERM=xterm-256color
export LD_LIBRARY_PATH=~/opencv/cv3.4/lib/:$LD_LIBRARY_PATH
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="half-life_cg"
#ZSH_THEME="ys"
ZSH_THEME="robbyrussell_cg"
#ZSH_THEME="robbyrussell"


plugins=(git
        autojump
        last-working-dir
        wd
        zsh-autosuggestions
        zsh-syntax-highlighting)
#zsh-autosuggestions zsh-syntax-highlighting  need to git clone from github

source $ZSH/oh-my-zsh.sh
alias cls='clear'
alias ll='ls -l -h'
alias la='ls -a'
alias vi='vim'
alias grep='grep --color=auto' #search
alias fdhm='find ~/ -name'
alias fd='find ./ -name'
alias py='python '
alias bpy='bpython '
alias q='..'
alias cleartrash='/bin/rm -rf ~/.trash/*'
alias rmhard='/bin/rm  -rf'
alias hm='hostname'
alias subl='sublime-text-dev '
alias lsnum='ls | wc -w'
alias start='dde-file-manager'

#git
alias gs='git status'
alias gcm='git commit'
alias t='tig'
alias gb='git branch'
alias gct='git checkout'
alias grt='git remote'

#alias -s py=vi       # 在命令行直接输入 python 文件，会用 vim 中打开，以下类似
alias -s js=vi
alias -s c=vi
alias -s txt=vi
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'
alias mk='/bin/bash /home/zhaoxu/Linux_tools/Useful_function/simple_compile.sh'
#alias del='/bin/bash   /home/zhaoxu/tools/remove.sh'
#alias rec='/bin/bash   /home/zhaoxu/tools/recover.sh'
#alias rm='echo Dont use rm!!!!!'
#little function
alias mkgo="makego"
makego()
{
    mkdir $1 && cd $1
}
# fix the color problem with zsh-syntax-highlighting
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=yellow
ZSH_HIGHLIGHT_STYLES[precommand]=fg=yellow
ZSH_HIGHLIGHT_STYLES[arg0]=fg=yellow
ZSH_HIGHLIGHT_STYLES[path]='fg=none'



