# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=/home/users/zhaoxu01.li/.oh-my-zsh
export TERM=xterm-256color
export ENV_PATH=/home/users/zhaoxu01.li/env_setting
source $ENV_PATH/zheng_env.sh

ZSH_THEME="robbyrussell_cg"

#autojump setting
[[ -s /home/users/zhaoxu01.li/.autojump/etc/profile.d/autojump.sh ]] && source /home/users/zhaoxu01.li/.autojump/etc/profile.d/autojump.sh


plugins=(git
        last-working-dir
        wd
        autojump
        zsh-autosuggestions
        zsh-syntax-highlighting)
#zsh-autosuggestions zsh-syntax-highlighting  need to git clone from github
source $ZSH/oh-my-zsh.sh
alias cls='clear'
alias ll='ls -l -h'
alias ks='ls'
alias sl='ls'
alias la='ls -a'
alias vi='vim'
alias grep='grep --color=auto' #search
alias fdhm='find ~/ -name'
alias fd='find ./ -name'
alias py='python '
alias bpy='bpython '
alias q='..'
alias cleartrash='/bin/rm -rf ~/.trash/*'
alias rmhard='/bin/rm  -rf'
alias hm='hostname'
alias subl='sublime-text-dev '
alias lsnum='ls | wc -w'
alias checksize='du -sh * | sort -n'
alias checkfilesize='du -sk -h'
alias checkdisk='df -hl'
eval $(thefuck --alias)
#Horizon Used
aladd="hdfs://hobot-bigdata-aliyun"
hzadd="hdfs://hobot-bigdata"
alias vim='~/tools/vim/bin/vim'
alias gosp='cd  /mnt/hdfs-data-3/data/zhaoxu01.li'
alias hs='/bin/bash hdfs dfs'
#git
alias gs='git status'
alias gcm='git commit'
alias t='tig'
alias gb='git branch'
alias gc='git checkout'
alias grt='git remote'
#alias -s py=vi       # 在命令行直接输入 python 文件，会用 vim 中打开，以下类似
alias -s js=vi
alias -s c=vi
alias -s txt=vi
alias tarunzip='tar xvf'
alias tarzip='tar cvf'
#alias -s zip='unzip'
alias -s bz2='tar -xjvf'
alias mk='/bin/bash /home/zhaoxu/Linux_tools/Useful_function/simple_compile.sh'
alias del='/bin/bash   ~/Linux_conf/Del_function/remove.sh'
alias rec='/bin/bash   ~/Linux_conf/Del_function/recover.sh'
alias rm='echo Dont use rm!!!!!'
alias isfile='py  ~/Linux_conf/Useful_function/checkIsfile.py'
#little function
alias mkgo="makego"
makego()
{
    mkdir $1 && cd $1
}
# fix the color problem with zsh-syntax-highlighting
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=yellow
ZSH_HIGHLIGHT_STYLES[precommand]=fg=yellow
ZSH_HIGHLIGHT_STYLES[arg0]=fg=yellow
ZSH_HIGHLIGHT_STYLES[path]='fg=none'



